export const INSTANTIATE_SCRIPTOR_REQUEST = 'INSTANTIATE_SCRIPTOR_REQUEST'
export const INSTANTIATE_SCRIPTOR_SUCCESS = 'INSTANTIATE_SCRIPTOR_SUCCESS'
export const INSTANTIATE_SCRIPTOR_FAILURE = 'INSTANTIATE_SCRIPTOR_FAILURE'

export const ADD_INSTRUCTION_REQUEST = 'ADD_INSTRUCTION_REQUEST'
export const ADD_INSTRUCTION_SUCCESS = 'ADD_INSTRUCTION_SUCCESS'
export const ADD_INSTRUCTION_FAILURE = 'ADD_INSTRUCTION_FAILURE'

export const SET_ELEMENTS = 'SET_ELEMENTS'
export const QUERY_ELEMENTS = 'QUERY_ELEMENTS'
